#################################
# Opacity
#################################
inactive-opacity = 1.0;   # 80% for inactive windows globally
active-opacity = 1.0;      # fully opaque active windows
frame-opacity = 1.0;
inactive-opacity-override = false;

opacity-rule = [
  "95:class_g = 'Alacritty'",  # 80% opacity for Alacritty
  "91:class_g = 'Rofi'",      # fully opaque Rofi
  "80:class_g = 'Polybar'"    # fully opaque Polybar
];
#################################
# Blur
#################################

